[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
# repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['kyazdani42/nvim-web-devicons']
hook_add = '''
lua << EOF
require'lualine'.setup {
  options = {
    icons_enabled = true,
    theme = 'auto',
    component_separators = { left = '', right = ''},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = true,
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch', 'diff', 'diagnostics'},
    lualine_c = {'filename'},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
EOF
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = ['nerdtree']
hook_add = '''
    " Ctrl+Nで起動
    map <C-n> <plug>NERDTreeTabsToggle<CR>
    " 起動時に有効化
    let g:nerdtree_tabs_open_on_console_startup=1
    "引数なしでvimを開いたらNERDTreeを起動、
    "引数ありならNERDTreeは起動しない、引数で渡されたファイルを開く。
    autocmd vimenter * if !argc() | NERDTree | endif
    "他のバッファをすべて閉じた時にNERDTreeが開いていたらNERDTreeも一緒に閉じる。
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# カラースキーム系1
[[plugins]]
repo = 'jacoborus/tender.vim'

# カラースキーム系2
[[plugins]]
repo = 'ulwlu/elly.vim'

# カラースキーム系3
[[plugins]]
repo = 'nanotech/jellybeans.vim'

# カラースキーム系4
[[plugins]]
repo = 'folke/tokyonight.nvim'

# コメントアウトしてくれるやつ
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    nmap <C-_> <Plug>(caw:hatpos:toggle)
    vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
        -- disable = { 'rust' },
    },
    indent = {
        enable = true, -- これを設定することでtree-sitterによるインデントを有効にできます
        disable = { 'rust' },
    },
    ensure_installed = 'all'
}
EOF
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>
nnoremap <leader>fg <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>
'''
